# Generated by Django 4.1.5 on 2023-02-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='text',
            field=models.TextField(default='本文を入力してください', verbose_name='本文'),
        ),
    ]
